### PR TITLE
Added a logoff function

### PR DESCRIPTION
**Pull request by MasonSchneider**
This adds the logOff function which takes a token and a callback and logsoff for that token.

### CODE REVIEW

**Comment by claudiowilson** [comment]
I've changed the CallApi command to automatically append the '&token' part. See SHA: 58030ad1918756ba529c53c7ed38a55789aca9aa So it should be safe to remove that in the commandText parameter.

Also, you shouldn't pass in true for the callback parameter. If you pass in true as the parameter to the callback then the receiving function will assume that there was an error. We're reserving the first parameter of the callback for Errors, so we want that to be null if there isn't an error. You should change that to callback(null)

**Comment by MasonSchneider** [comment]
The LogOff function has been modified to work with the token standards as well as returning errors in the first parameter.

**Comment by claudiowilson** [comment]
Nice! One last thing, can you add an exports so that the function is exposed when required by node? Look at the exports.LogOn in SHA: cbd9961b9dc5f317a6df7795cacf926e4e23fc75 Just add an exports.LogOff version. We want to do this for all the functions we expose to the user of our module (we obviously want them to be able to log off).

**Comment by claudiowilson** [comment]
Yay! Approved

**Comment by MasonSchneider** [comment]
Yay! My first pull request has been pulled!

**Comment by claudiowilson** [comment]
I merged my first pull request!

**Pull request merged**
